name: ashesh
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pytorch
  - torchvision
  - netCDF4
  - opencv
  - scipy
  - matplotlib
  - scikit-image
  - scikit-learn-intelex
  - pandas
  - jupyterlab
  - numpy
  - wandb
